---
- name: Install Apache Web Server
  hosts: webservers:database_servers
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started

    - name: Enabled Apache service on boot
      service:
        name: apache2
        enabled: true
